repos:
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.3
    hooks:
      - id: shellcheck
      - id: shfmt
